<a href="https://colab.research.google.com/github/darshanvyas36/Oasis-Infobyte-tasks/blob/main/Data_Preprocessing_Template.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing

## Importing the libraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot

## Importing Dataset

In [5]:
data_set = pd.read_csv("covid_data_set.csv")
X = data_set.iloc[:, :-1].values
Y = data_set.iloc[:, -1].values

In [6]:
print(X)

[[10.0 'Normal' 'no' 'no' 97.0]
 [12.0 'Normal' 'no' 'no' 97.0]
 [15.0 'Normal' 'no' 'no' 94.0]
 [10.0 'Normal' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 94.0]
 [12.0 'Moderate' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 93.0]
 [15.0 'Moderate' 'no' 'no' 92.0]
 [18.0 'Moderate' 'no' 'no' 66.0]
 [19.0 'Normal' 'no' 'no' 92.0]
 [20.0 'Normal' 'no' 'no' 93.0]
 [17.0 'Normal' 'no' 'no' 93.0]
 [16.0 'Normal' 'no' 'no' 92.0]
 [18.0 'Normal' 'no' 'no' 93.0]
 [20.0 'Normal' 'no' 'no' 92.0]
 [25.0 'Moderate' 'no' 'no' 93.0]
 [24.0 'Moderate' 'no' 'no' 92.0]
 [26.0 'High' 'no' 'no' 94.0]
 [28.0 'Normal' 'no' 'no' 99.0]
 [29.0 'Normal' 'no' 'no' 93.0]
 [30.0 'Moderate' 'no' 'no' 62.0]
 [19.0 'Normal' 'no' 'no' 89.0]
 [25.0 'Normal' 'no' 'yes' 86.0]
 [26.0 'Normal' 'no' 'no' nan]
 [28.0 'Normal' 'no' 'no' 89.0]
 [30.0 'Moderate' 'yes' 'no' 86.0]
 [35.0 'Moderate' 'no' 'no' 89.0]
 [32.0 'Moderate' 'no' 'yes' 84.0]
 [nan 'Moderate' 'yes' 'no' 90.0]
 [32.0 'Moderate' 'no' 'no' 89.0]
 [35.0 'Modera

In [7]:
print(Y)

['No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes'
 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes'
 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'Yes'
 'Yes' 'No' 'Yes' 'Yes' 'Yes']





## Handling Missing Data

In [8]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy='mean')

# imputer.fit(X[:, 0:1])
# X[:, 0:1] = imputer.transform(X[:, 0:1])
# X

In [9]:
# imputer.fit(X[:, 4:5])
# X[:, 4:5] = imputer.transform(X[:, 4:5])
# X

In [10]:
imputer.fit(X[:, 0:5:4])
X[:,0:5:4] = imputer.transform(X[:,0:5:4])
X

array([[10.0, 'Normal', 'no', 'no', 97.0],
       [12.0, 'Normal', 'no', 'no', 97.0],
       [15.0, 'Normal', 'no', 'no', 94.0],
       [10.0, 'Normal', 'no', 'no', 97.0],
       [13.0, 'Moderate', 'no', 'no', 94.0],
       [12.0, 'Moderate', 'no', 'no', 97.0],
       [13.0, 'Moderate', 'no', 'no', 93.0],
       [15.0, 'Moderate', 'no', 'no', 92.0],
       [18.0, 'Moderate', 'no', 'no', 66.0],
       [19.0, 'Normal', 'no', 'no', 92.0],
       [20.0, 'Normal', 'no', 'no', 93.0],
       [17.0, 'Normal', 'no', 'no', 93.0],
       [16.0, 'Normal', 'no', 'no', 92.0],
       [18.0, 'Normal', 'no', 'no', 93.0],
       [20.0, 'Normal', 'no', 'no', 92.0],
       [25.0, 'Moderate', 'no', 'no', 93.0],
       [24.0, 'Moderate', 'no', 'no', 92.0],
       [26.0, 'High', 'no', 'no', 94.0],
       [28.0, 'Normal', 'no', 'no', 99.0],
       [29.0, 'Normal', 'no', 'no', 93.0],
       [30.0, 'Moderate', 'no', 'no', 62.0],
       [19.0, 'Normal', 'no', 'no', 89.0],
       [25.0, 'Normal', 'no', 'yes', 86.

## Encoding Categorical Data

### Encoding independent variables

In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [12]:
ct = ColumnTransformer(transformers=[("encoder", OneHotEncoder(), [1])],remainder='passthrough')
X=np.array(ct.fit_transform(X))
X

array([[0.0, 0.0, 1.0, 10.0, 'no', 'no', 97.0],
       [0.0, 0.0, 1.0, 12.0, 'no', 'no', 97.0],
       [0.0, 0.0, 1.0, 15.0, 'no', 'no', 94.0],
       [0.0, 0.0, 1.0, 10.0, 'no', 'no', 97.0],
       [0.0, 1.0, 0.0, 13.0, 'no', 'no', 94.0],
       [0.0, 1.0, 0.0, 12.0, 'no', 'no', 97.0],
       [0.0, 1.0, 0.0, 13.0, 'no', 'no', 93.0],
       [0.0, 1.0, 0.0, 15.0, 'no', 'no', 92.0],
       [0.0, 1.0, 0.0, 18.0, 'no', 'no', 66.0],
       [0.0, 0.0, 1.0, 19.0, 'no', 'no', 92.0],
       [0.0, 0.0, 1.0, 20.0, 'no', 'no', 93.0],
       [0.0, 0.0, 1.0, 17.0, 'no', 'no', 93.0],
       [0.0, 0.0, 1.0, 16.0, 'no', 'no', 92.0],
       [0.0, 0.0, 1.0, 18.0, 'no', 'no', 93.0],
       [0.0, 0.0, 1.0, 20.0, 'no', 'no', 92.0],
       [0.0, 1.0, 0.0, 25.0, 'no', 'no', 93.0],
       [0.0, 1.0, 0.0, 24.0, 'no', 'no', 92.0],
       [1.0, 0.0, 0.0, 26.0, 'no', 'no', 94.0],
       [0.0, 0.0, 1.0, 28.0, 'no', 'no', 99.0],
       [0.0, 0.0, 1.0, 29.0, 'no', 'no', 93.0],
       [0.0, 1.0, 0.0, 30.0, 'no', 'no',

### Encoding dependent variables

In [14]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y = le.fit_transform(Y)

In [15]:
print(Y)

[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1]


## Splitting data into Test set & Training Set


In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X , Y, test_size=0.2 ,random_state = 42)

In [17]:
print(X_train)

[[1.0 0.0 0.0 86.0 'yes' 'yes' 71.0]
 [0.0 1.0 0.0 35.0 'no' 'yes' 92.0]
 [1.0 0.0 0.0 75.0 'no' 'yes' 72.0]
 [1.0 0.0 0.0 42.0 'no' 'no' 92.0]
 [1.0 0.0 0.0 74.0 'yes' 'yes' 75.0]
 [1.0 0.0 0.0 62.0 'yes' 'yes' 68.0]
 [0.0 1.0 0.0 24.0 'no' 'no' 92.0]
 [0.0 1.0 0.0 48.0 'no' 'yes' 93.0]
 [1.0 0.0 0.0 58.0 'no' 'no' 70.0]
 [0.0 1.0 0.0 45.130434782608695 'yes' 'no' 90.0]
 [0.0 1.0 0.0 15.0 'no' 'no' 92.0]
 [0.0 0.0 1.0 70.0 'no' 'yes' 88.0]
 [1.0 0.0 0.0 52.0 'yes' 'yes' 80.0]
 [1.0 0.0 0.0 60.0 'yes' 'yes' 68.0]
 [1.0 0.0 0.0 54.0 'yes' 'yes' 70.0]
 [0.0 0.0 1.0 29.0 'no' 'no' 93.0]
 [1.0 0.0 0.0 78.0 'yes' 'yes' 71.0]
 [1.0 0.0 0.0 36.0 'yes' 'no' 90.0]
 [0.0 1.0 0.0 30.0 'yes' 'no' 86.0]
 [1.0 0.0 0.0 50.0 'yes' 'yes' 77.0]
 [0.0 0.0 1.0 18.0 'no' 'no' 93.0]
 [1.0 0.0 0.0 69.0 'no' 'yes' 53.0]
 [0.0 0.0 1.0 10.0 'no' 'no' 97.0]
 [1.0 0.0 0.0 26.0 'no' 'no' 94.0]
 [0.0 1.0 0.0 18.0 'no' 'no' 66.0]
 [1.0 0.0 0.0 62.0 'yes' 'yes' 69.0]
 [0.0 1.0 0.0 13.0 'no' 'no' 93.0]
 [1.0 0.0 0.0 4

In [18]:
print(X_test)

[[0.0 0.0 1.0 25.0 'no' 'yes' 86.0]
 [0.0 0.0 1.0 10.0 'no' 'no' 97.0]
 [1.0 0.0 0.0 68.0 'yes' 'no' 67.0]
 [0.0 1.0 0.0 13.0 'no' 'no' 94.0]
 [1.0 0.0 0.0 59.0 'yes' 'no' 68.0]
 [0.0 0.0 1.0 28.0 'no' 'no' 99.0]
 [0.0 0.0 1.0 20.0 'no' 'no' 93.0]
 [1.0 0.0 0.0 46.0 'yes' 'no' 91.0]
 [1.0 0.0 0.0 53.0 'yes' 'no' 55.0]
 [0.0 0.0 1.0 16.0 'no' 'no' 92.0]
 [1.0 0.0 0.0 38.0 'no' 'no' 75.0]
 [0.0 0.0 1.0 19.0 'no' 'no' 92.0]
 [1.0 0.0 0.0 94.0 'yes' 'yes' 64.0]
 [0.0 1.0 0.0 12.0 'no' 'no' 97.0]]


In [19]:
print(Y_train)

[1 0 1 0 1 1 0 0 1 0 0 0 1 1 1 0 1 0 0 1 0 1 0 0 1 1 0 0 1 1 1 0 0 1 0 1 0
 1 1 0 0 0 1 1 0 1 1 0 1 0 0 0 1 0 0 1]


In [20]:
print(Y_test)

[0 0 1 0 1 0 0 0 1 0 1 0 1 0]


## Feature Scaling

In [28]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,6:] = sc.fit_transform(X_train[:, 6:])
X_test[:,6:] = sc.fit_transform(X_test[:, 6:])

In [29]:
print(X_train)

[[1.0 0.0 0.0 86.0 'yes' 'yes' -0.9941858494300263]
 [0.0 1.0 0.0 35.0 'no' 'yes' 0.9574354145081887]
 [1.0 0.0 0.0 75.0 'no' 'yes' -0.9012515035282066]
 [1.0 0.0 0.0 42.0 'no' 'no' 0.9574354145081887]
 [1.0 0.0 0.0 74.0 'yes' 'yes' -0.6224484658227474]
 [1.0 0.0 0.0 62.0 'yes' 'yes' -1.2729888871354855]
 [0.0 1.0 0.0 24.0 'no' 'no' 0.9574354145081887]
 [0.0 1.0 0.0 48.0 'no' 'yes' 1.0503697604100086]
 [1.0 0.0 0.0 58.0 'no' 'no' -1.0871201953318461]
 [0.0 1.0 0.0 45.130434782608695 'yes' 'no' 0.7715667227045492]
 [0.0 1.0 0.0 15.0 'no' 'no' 0.9574354145081887]
 [0.0 0.0 1.0 70.0 'no' 'yes' 0.5856980309009097]
 [1.0 0.0 0.0 52.0 'yes' 'yes' -0.1577767363136485]
 [1.0 0.0 0.0 60.0 'yes' 'yes' -1.2729888871354855]
 [1.0 0.0 0.0 54.0 'yes' 'yes' -1.0871201953318461]
 [0.0 0.0 1.0 29.0 'no' 'no' 1.0503697604100086]
 [1.0 0.0 0.0 78.0 'yes' 'yes' -0.9941858494300263]
 [1.0 0.0 0.0 36.0 'yes' 'no' 0.7715667227045492]
 [0.0 1.0 0.0 30.0 'yes' 'no' 0.3998293390972701]
 [1.0 0.0 0.0 50.0 'yes' 

In [30]:
print(X_test)

[[0.0 0.0 1.0 25.0 'no' 'yes' 0.1720510299257006]
 [0.0 0.0 1.0 10.0 'no' 'no' 0.9513409890009328]
 [1.0 0.0 0.0 68.0 'yes' 'no' -1.1739952630224277]
 [0.0 1.0 0.0 13.0 'no' 'no' 0.7388073637985968]
 [1.0 0.0 0.0 59.0 'yes' 'no' -1.1031507212883158]
 [0.0 0.0 1.0 28.0 'no' 'no' 1.0930300724691568]
 [0.0 0.0 1.0 20.0 'no' 'no' 0.6679628220644848]
 [1.0 0.0 0.0 46.0 'yes' 'no' 0.5262737385962607]
 [1.0 0.0 0.0 53.0 'yes' 'no' -2.024129763831772]
 [0.0 0.0 1.0 16.0 'no' 'no' 0.5971182803303727]
 [1.0 0.0 0.0 38.0 'no' 'no' -0.6072389291495315]
 [0.0 0.0 1.0 19.0 'no' 'no' 0.5971182803303727]
 [1.0 0.0 0.0 94.0 'yes' 'yes' -1.3865288882247637]
 [0.0 1.0 0.0 12.0 'no' 'no' 0.9513409890009328]]


In [36]:
# Y_train[:, 3:4] = sc.fit_transform(Y_train[:, 3:4])
# Y_test[:,3:4] = sc.fit_transform(Y_test[:, 3:4])